site_name: Modelo de Ising
repo_url: https://github.com/ali-sacasa/Modelo-de-Ising/
theme:
  name: mkdocs
  features: 
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate     
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo Oscuro
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Inicio: index.md
  - Uso: usage.md

  - Teoría:
    - Modelo de Ising: Teoría/Modelo_de_ising.md
    - Enfoque de resolución propuesto: Teoría/Enfoque_de_resolución_propuesto.md


  - Código:
    - Módulos en Python: Código/Módulos_Python.md
    - Módulos en C++: Código/Módulos_C++.md
    - Implementación Paralelizada en C++: Código/Implementación_paralelizada_C++.md

  - Referencias: Referencias/referencias.md
    

plugins:  
  - search
  - macros