site_name: Modelo de Ising
repo_url: https://example.com
nav:
  - Inicio: index.md
  - Uso: usage.md
theme:
  name: mkdocs
  features: 
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate     
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo Oscuro
markdown_extensions:
  - admonition
  - codehilite
  - toc:    
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite   
  - pymdownx.magiclink
  - pymdownx.betterem:
      smart_enable: all     
  - pymdownx.caret      

nav:
  - Inicio: index.md
  - Uso: usage.md

  - Teoría:
    - Modelo de Ising: Modelo_de_ising.md
    - Enfoque de resolución propuesto: Enfoque_de_resolución_propuesto.md


  . Código:
    - Módulos en Python: Modulos_Python.md
    - Módulos en C++: Modulos_C++.md
    - Implementación Paralelizada en Python: Implementación_del_modelo_de_Ising.md
    - Implementación Paralelizada en C++: Implementación_en_C++.md
  - Resultados, discusión y conclusiones:
    - Resultados: Resultados.md
    - Discusión: Discusion.md
    - Conclusiones: Conclusiones.md

  - Referencias: referencias.md
    

plugins:  
  - search
  - mkdocs_macros   